language: node_js
node_js: '10'
cache: npm
addons:
  chrome: stable
branches:
  only:
  - master
install: npm install
script:
- ng lint
- npm run test:headless
- node publish-pact.js
dd:
  secure: pfedPM8ZyUPAFog0OgFUwHupwHvz0zLwGEc6PJAauWsbOS7rCyFG/Nh9QlXPLG+86OuUlm3xm5UxrYPVoOr+NYGlgEqWSaFTOatWqskJIY1YXkVuQ1+l0enQ97lDUez9LqvWSYr43prRQRPf5FEOzXcByV7WiVYR9ZVPjQAt1H33PhkKeBC0FeK29Oc0HP7CXBlfa+06x3tzNCpPWkOG5ilqGqjrauSCIAXBaE6wAAHPTJeh+FQLs5sy3E82mpihspCkLkn1FY5dJptBpRuyC2Z05Cibof0wX0gzsv2JznJbrP+uP+OGXbXO8CTWFkOMmMxXXZ758fV5ikqNAkNeSyO/AwLvK4N2FnWE/lHhRUIvDl4IEJ8L/J0OgiW0RLWPmLQ860Su5nb2/OhRz+UWpU5E3Y2NV38JWJO/TjUYKRhFc3EeS0UA5fc8+OJv1BwXZ3u87hVzhTHJQqA2rjKH0sjDdZuJ4bpYI/XhbKpyuZ6JGpHfRYWVu+IDnpI/cFwsYacVxNdusKJx1fM5etCYQnpFqspJTEyydSs0EuFIs9FHBc2eomJiR7XPFpfrxLlcN8Xitiqu6olCpPa3z9NLULOKdQtEdXC5kKThxiCOP/nex0IXxKYvpAt/oIPE7JO1yLmLaUXztjEg/pFHaabal5HjpB/7pk9YhY1G4C1ODhA=
