export enum Metrics {
  Network = "Network",
  ErrorRate = "Error Rate",
  Threads = "Virtual Users",
  Throughput = "Throughput",
  ResponseTimeAvg = "Response Time [avg]",
  ResponseTimeMin = "Response Time [min]",
  ResponseTimeMax = "Response Time [max]",
  ResponseTimeP90 = "Response Time [P90]",
  ResponseTimeP95 = "Response Time [P95]",
  ResponseTimeP99 = "Response Time [P99]",
  StatusCodeInTime = "Status Code In Time",
  ResponseTimeRaw = "Raw Response Time",
  LatencyAvg = "Latency [avg]",
  ConnectAvg = "Connection [avg]",
}
